---
- name: Deploy static website to web servers
  hosts: webservers
  become: yes

  tasks:
    - name: Copy website files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/www/html/
      with_fileglob:
        - "*.html"
        - "*.css"
        - "*.js"
        - "*.jpg"
        - "*.png"

    - name: Restart Apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
